server:
  address: 0.0.0.0
  port: 8080

spring:
  config:
    activate:
      on-profile: docker

  cloud:
    gateway:

      globalcors:
        add-to-simple-url-handler-mapping: true

        cors-configurations:
          '[/**]':
            allowedOrigins:
              - "http://localhost:5173"

            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS

            allowedHeaders:
              - "*"

            exposedHeaders:
              - Authorization

            allowCredentials: true

            maxAge: 3600

      server:
        webflux:

          routes:

            - id: user-service
              uri: http://user-management:8081
              predicates:
                - Path=/api/public/login,/api/public/register,/api/public/forgot-password,/api/public/reset-password,/api/public/refresh-token,/api/public/request-restore,/api/public/restore,/api/public/verify-email,/api/public/resend-verification-email

            - id: flight-service
              uri: http://flight-management:8082
              predicates:
                - Path=/api/public/flights/**,/api/admin/flight-instances/**,/api/public/seats/**,/api/private/flights/**,/api/flights/**,/api/aircrafts/**,/api/airlines/**,/api/airports/**,/api/baggage-policies/**,/api/flight-amenities/**,/api/flight-fares/**,/api/flight-status-info/**

            - id: booking-service
              uri: http://booking-management:8083
              predicates:
                - Path=/api/private/user/bookings,/api/private/user/bookings/**,/api/private/admin/bookings,/api/private/admin/bookings/**
              filters:
                - PreserveHostHeader

            - id: booking-internal-service
              uri: http://booking-management:8083
              predicates:
                - Path=/api/internal/bookings/**

            - id: payment-service
              uri: http://payment-management:8084
              predicates:
                - Path=/api/private/payments/**,/api/admin/payments/**

            - id: payment-webhook-service
              uri: http://payment-management:8084
              predicates:
                - Path=/api/public/webhooks/**

            - id: notification-service
              uri: http://notification-management:8085
              predicates:
                - Path=/api/private/notifications/**,/api/private/admin/notifications/**

            - id: notification-internal-service
              uri: http://notification-management:8085
              predicates:
                - Path=/api/internal/notifications/**

            - id: user-docs
              uri: http://user-management:8081
              predicates:
                - Path=/user/v3/api-docs
              filters:
                - RewritePath=/user/(?<segment>.*), /${segment}

            - id: flight-docs
              uri: http://flight-management:8082
              predicates:
                - Path=/flight/v3/api-docs
              filters:
                - RewritePath=/flight/(?<segment>.*), /${segment}

            - id: booking-docs
              uri: http://booking-management:8083
              predicates:
                - Path=/booking/v3/api-docs
              filters:
                - RewritePath=/booking/(?<segment>.*), /${segment}

            - id: payment-docs
              uri: http://payment-management:8084
              predicates:
                - Path=/payment/v3/api-docs
              filters:
                - RewritePath=/payment/(?<segment>.*), /${segment}

            - id: notification-docs
              uri: http://notification-management:8085
              predicates:
                - Path=/notification/v3/api-docs
              filters:
                - RewritePath=/notification/(?<segment>.*), /${segment}

logging:
  level:
    "[org.springframework.cloud.gateway]": DEBUG
    "[org.springframework.web.cors]": DEBUG

springdoc:
  swagger-ui:
    urls:
      - name: User Management
        url: /user/v3/api-docs

      - name: Flight Management
        url: /flight/v3/api-docs

      - name: Booking Management
        url: /booking/v3/api-docs

      - name: Payment Management
        url: /payment/v3/api-docs

      - name: Notification Management
        url: /notification/v3/api-docs