server:
  port: 8080

spring:
  config:
    activate:
      on-profile: dev

  cloud:
    gateway:
      server:
        webflux:
          routes:

            #################################################
            # USER MANAGEMENT
            #################################################
            - id: user-service
              uri: http://localhost:8081
              predicates:
                - Path=/api/public/**,/api/private/users/**

            #################################################
            # FLIGHT MANAGEMENT
            #################################################
            - id: flight-service
              uri: http://localhost:8082
              predicates:
                - Path=/api/flights/**,/api/aircrafts/**,/api/airlines/**,/api/airports/**,/api/baggage-policies/**,/api/flight-amenities/**,/api/flight-fares/**,/api/flight-status-info/**

            #################################################
            # BOOKING MANAGEMENT
            #################################################
            - id: booking-service
              uri: http://localhost:8083
              predicates:
                - Path=/api/private/bookings/**,/api/private/user/bookings/**,/api/private/admin/bookings/**

            #################################################
            # USER SWAGGER
            #################################################
            - id: user-docs
              uri: http://localhost:8081
              predicates:
                - Path=/user/v3/api-docs
              filters:
                - RewritePath=/user/(?<segment>.*), /${segment}

            #################################################
            # FLIGHT SWAGGER
            #################################################
            - id: flight-docs
              uri: http://localhost:8082
              predicates:
                - Path=/flight/v3/api-docs
              filters:
                - RewritePath=/flight/(?<segment>.*), /${segment}

            #################################################
            # BOOKING SWAGGER
            #################################################
            - id: booking-docs
              uri: http://localhost:8083
              predicates:
                - Path=/booking/v3/api-docs
              filters:
                - RewritePath=/booking/(?<segment>.*), /${segment}

logging:
  level:
    "[org.springframework.cloud.gateway]": INFO

springdoc:
  swagger-ui:
    urls:
      - name: User Management
        url: /user/v3/api-docs
      - name: Flight Management
        url: /flight/v3/api-docs
      - name: Booking Management
        url: /booking/v3/api-docs