server:
  port: 8080

spring:
  application:
    name: api-gateway

  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}

app:
  jwt:
    secret-key: ${JWT_SECRET}
    expiration-time: ${JWT_EXPIRATION_TIME:1800000}
    refresh-expiration-time: ${JWT_REFRESH_EXPIRATION_TIME:604800000}

logging:
  level:
    "[org.springframework.cloud.gateway]": DEBUG