services:
  mysql:
    image: mysql:8.4
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: flightbooking
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  usermanagment:
    build: .
    container_name: usermanagment
    restart: always
    depends_on:
      - mysql
    env_file:
      - .env
    ports:
      - "8080:8080"

volumes:
  mysql_data: