spring:
  application:
    name: UserPreview
  mongodb:
    uri: mongodb+srv://FlightBooking:Vijay9299@springprojectmain.dwtx9qs.mongodb.net/Booking?retryWrites=true&w=majority

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html

app:
  jwt:
    secret: sdihwuefhfhwakldjjqwoiruir49556ejfeifhi855wdwd8fjffiuf5
    expiration: 86400000
    refreshExpiration: 604800000