server:
  port: 8084

spring:
  application:
    name: payment-management

  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}

  cloud:
    openfeign:
      okhttp:
        enabled: true
      httpclient:
        hc5:
          enabled: false

logging:
  level:
    "[org.hibernate.SQL]": DEBUG
    "[org.hibernate.orm.schema]": DEBUG
    "[org.hibernate.tool.schema]": DEBUG
    "[com.project.payment]": INFO

  file:
    name: logs/payment-management.log

app:

  jwt:
    secret-key: ${JWT_SECRET}
    expiration-time: ${JWT_EXPIRATION_TIME:900000}
    refresh-expiration-time: ${JWT_REFRESH_EXPIRATION_TIME:604800000}